"""memdag_claude — manage the memdag-owned block in your Claude Code CLAUDE.md.

CLAUDE.md is the always-loaded global instruction file for the Claude Code CLI.
memdag needs the agent to know HOW to use the memory store (the per-fact file
format, the channels, that MEMORY.md is generated and must not be hand-edited).
This module owns a single delimited block inside CLAUDE.md and keeps it current —
everything outside the block is the user's and is never touched.

    <!-- memdag:managed:start -->
    ...the memory protocol (regenerated by memdag)...
    <!-- memdag:managed:end -->

`memdag claude-sync` behavior (all writes atomic via tmp+replace, fail-safe):
  - file absent          -> write the shipped template (preamble + block).
  - file present, block   -> replace the block body with the canonical text
                             (idempotent: a no-op when already current).
  - file present, no block-> back up to CLAUDE.md.bak, then append the block.

Target is ``~/.claude/CLAUDE.md``; override with ``$CLAUDE_MD_PATH``.
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

START = "<!-- memdag:managed:start -->"
END = "<!-- memdag:managed:end -->"

# The canonical managed-block body (between the markers). Identity-free: it
# describes the mechanism, never a specific user.
CANONICAL = """## Memory protocol (managed by memdag — do not hand-edit this block)

You have a persistent, file-based memory store. Each memory is ONE fact in ONE
file under your memory directory, with frontmatter:

```
---
name: <short-kebab-case-slug>
description: <one-line summary; used to judge relevance on recall>
type: user | personal | feedback | project | reference
source: user | session:<YYYY-MM-DD>
salience: <0.00-1.00>      # optional: how strongly to encode (affect-weighted)
---

<the fact. For feedback/project, follow with **Why:** and **How to apply:** lines.
Link related memories with [[their-name]].>
```

**Channels** (trust, highest first): `endorsed > user > agent-derived > external`.
`user_*` / `feedback_*` / `personal_*` files are endorsed (pinned, never auto-dropped);
`project_*` / `reference_*` are user-channel and decay out of the index when unused.

**MEMORY.md is the always-loaded index, and it is GENERATED** from the store on
session end by the `memdag bridge-render` Stop hook. Do NOT hand-edit MEMORY.md —
edit the per-fact files and let it regenerate. Keep it under ~16 KB.

To capture a session's worth of facts, use **`/saveall`**. Before saving, check
whether a file already covers the fact and update it instead of duplicating; delete
(tombstone) memories that turn out to be wrong."""

PREAMBLE = """# CLAUDE.md

Your project- and user-level instructions live in this file. Add your own guidance
above or below the memdag-managed block; memdag only ever rewrites the block between
its markers.
"""


# --- pure helpers (no IO; unit-testable) -------------------------------------

def render_block() -> str:
    """The full managed block, markers included."""
    return f"{START}\n{CANONICAL.strip()}\n{END}"


def render_template() -> str:
    """A complete generic CLAUDE.md for the file-absent (seed) path."""
    return f"{PREAMBLE.rstrip()}\n\n{render_block()}\n"


def upsert(text: str, block: str):
    """Insert/refresh *block* in *text*. Returns (new_text, action).

    action: 'replace' (block existed, body changed), 'noop' (already current),
    or 'append' (no block present yet)."""
    if START in text and END in text:
        pre = text[:text.index(START)]
        post = text[text.index(END) + len(END):]
        new = pre + block + post
        return new, ("noop" if new == text else "replace")
    # no block yet: append, separated by exactly one blank line
    base = text.rstrip("\n")
    sep = "\n\n" if base else ""
    return f"{base}{sep}{block}\n", "append"


# --- IO ----------------------------------------------------------------------

def default_path() -> Path:
    env = os.environ.get("CLAUDE_MD_PATH")
    if env:
        return Path(env).expanduser()
    return Path.home() / ".claude" / "CLAUDE.md"


def _atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)


def sync(path=None, *, dry_run: bool = False) -> dict:
    """Seed / refresh the managed block in CLAUDE.md. Returns a result dict
    {path, action, changed}. Never raises for the absent/present cases; an
    unexpected IO error propagates to the caller (the CLI wraps it fail-safe)."""
    path = Path(path).expanduser() if path else default_path()
    block = render_block()

    if not path.exists():
        new_text, action = render_template(), "seed"
    else:
        existing = path.read_text(encoding="utf-8")
        new_text, action = upsert(existing, block)

    changed = action not in ("noop",)
    if changed and not dry_run:
        if action == "append":
            # preserve the user's file before we touch it
            bak = path.with_suffix(path.suffix + ".bak")
            bak.write_text(path.read_text(encoding="utf-8"), encoding="utf-8")
        _atomic_write(path, new_text)
    return {"path": str(path), "action": action, "changed": changed}


# --- CLI ---------------------------------------------------------------------

def _cmd_claude_sync(args):
    if args.print_only:
        print(render_block())
        return
    try:
        res = sync(path=args.path, dry_run=args.dry_run)
    except Exception as exc:  # noqa: BLE001 — never break a hook chain
        print(f"[claude-sync] skipped (CLAUDE.md unchanged): {exc!r}")
        return
    verb = {"seed": "seeded", "append": "appended block to",
            "replace": "refreshed block in", "noop": "already current:"}[res["action"]]
    print(f"[claude-sync] {verb} {res['path']}")


def register(sub) -> None:
    p = sub.add_parser(
        "claude-sync",
        help="seed/refresh the memdag-managed memory block in CLAUDE.md")
    p.add_argument("--path", default=None,
                   help="CLAUDE.md path (default: $CLAUDE_MD_PATH or ~/.claude/CLAUDE.md)")
    p.add_argument("--print-only", action="store_true",
                   help="print the managed block and write nothing")
    p.add_argument("--dry-run", action="store_true",
                   help="report what would change without writing")
    p.set_defaults(func=_cmd_claude_sync)


def main(argv=None) -> None:
    for s in (sys.stdout, sys.stderr):
        try:
            s.reconfigure(encoding="utf-8")
        except Exception:
            pass
    ap = argparse.ArgumentParser(prog="memdag_claude", description=__doc__)
    ap.add_argument("--path", default=None)
    ap.add_argument("--print-only", action="store_true")
    ap.add_argument("--dry-run", action="store_true")
    _cmd_claude_sync(ap.parse_args(argv))


if __name__ == "__main__":
    main()
