"""memsom_claude — manage the memsom-owned block in your Claude Code CLAUDE.md.

CLAUDE.md is the always-loaded global instruction file for the Claude Code CLI.
memsom needs the agent to know HOW to use the memory store (the per-fact file
format, the channels, that MEMORY.md is generated and must not be hand-edited).
This module owns a single delimited block inside CLAUDE.md and keeps it current —
everything outside the block is the user's and is never touched.

    <!-- memsom:managed:start -->
    ...the memory protocol (regenerated by memsom)...
    <!-- memsom:managed:end -->

`memsom claude-sync` behavior (all writes atomic via tmp+replace, fail-safe):
  - file absent          -> write the shipped template (preamble + block).
  - file present, block   -> replace the block body with the canonical text
                             (idempotent: a no-op when already current).
  - file present, no block-> back up to CLAUDE.md.bak, then append the block.

Target is ``~/.claude/CLAUDE.md``; override with ``$CLAUDE_MD_PATH``.
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

START = "<!-- memsom:managed:start -->"
END = "<!-- memsom:managed:end -->"
# Legacy markers from the pre-2026-07-01 "memdag" era. Testers wired before the
# rename carry these; upsert() migrates such a block in place (replacing it with
# the new memsom markers) instead of appending a duplicate.
LEGACY_START = "<!-- memdag:managed:start -->"
LEGACY_END = "<!-- memdag:managed:end -->"

# The canonical managed-block body (between the markers). Identity-free: it
# describes the mechanism, never a specific user.
CANONICAL = """## Memory protocol (managed by memsom — do not hand-edit this block)

You have a persistent, file-based memory store. Each memory is ONE fact in ONE
file under your memory directory, with frontmatter:

```
---
name: <short-kebab-case-slug>
description: <one-line summary; used to judge relevance on recall>
type: user | personal | feedback | project | reference
source: user | session:<YYYY-MM-DD>
salience: <0.00-1.00>      # optional: how strongly to encode (affect-weighted)
---

<the fact. For feedback/project, follow with **Why:** and **How to apply:** lines.
Link related memories with [[their-name]].>
```

**Channels** (trust, highest first): `endorsed > user > agent-derived > external`.
`user_*` / `feedback_*` / `personal_*` files are endorsed (pinned, never auto-dropped);
`project_*` / `reference_*` are user-channel and decay out of the index when unused.

**MEMORY.md is the always-loaded index, and it is GENERATED** from the store on
session end by the `memsom bridge-render` Stop hook. Don't rewrite its hooks or
content by hand — edit the per-fact files and let it regenerate. Keep it under ~16 KB.

**But DO add the index line when you create a NEW memory** — one
`- [Title](file.md) — hook` bullet under the right `##` section. This is the one
hand-edit that IS required: the importer reads a memory's `section` from the
MEMORY.md line (falling back to the file's own `section:` frontmatter), and the
digest only renders memories that have one. A new file with neither is written to
disk, stays fully searchable — and never loads into context. So: add the line, or
put `section:` / `index_title:` / `index_hook:` in the file's frontmatter. Do one.

**If MEMORY.md is near the 16 KB cap, reclaim BEFORE adding to it.** Over budget,
the digest sheds the lowest-RS entries to fit; that is a transient, recoverable
drop, but it means your write can silently cost an unrelated memory its slot.

To capture a session's worth of facts, use **`/saveall`**. Before saving, check
whether a file already covers the fact and update it instead of duplicating; delete
(tombstone) memories that turn out to be wrong.

**Changing values live in FACT files, referenced — never copied.** A measured
value (benchmark, version, dose, income) goes in ONE `fact_<name>.md` with
`type: fact`, `value:`, `last-verified:`, `section: Facts` frontmatter; other
memories write `[[fact_<name>]]` (the filename stem) where the number would go.
Read surfaces substitute the current value automatically, so referencing
memories can never go stale. Update a value with `memsom fact-set fact_<name>
<value>` (or edit the file) — never by rewriting the memories that cite it.
If one fact is only true because of another (a measurement on specific
hardware), add `depends_on: fact_<other>` so retiring the dependency flags it
for reverification."""

PREAMBLE = """# CLAUDE.md

Your project- and user-level instructions live in this file. Add your own guidance
above or below the memsom-managed block; memsom only ever rewrites the block between
its markers.
"""


# --- pure helpers (no IO; unit-testable) -------------------------------------

def render_block() -> str:
    """The full managed block, markers included."""
    return f"{START}\n{CANONICAL.strip()}\n{END}"


def render_template() -> str:
    """A complete generic CLAUDE.md for the file-absent (seed) path."""
    return f"{PREAMBLE.rstrip()}\n\n{render_block()}\n"


def _find_blocks(text: str, start: str, end: str):
    """Well-ordered, non-overlapping (i, j) spans of start..end blocks in *text*.

    Returns None when the markers are malformed: an orphan START or END, an END
    before its START (reversed), or a nested/duplicate START inside a block.
    The old presence-only check let a lost END append a duplicate block and let
    reversed markers swallow the user content between them."""
    spans = []
    pos = 0
    while True:
        i = text.find(start, pos)
        j = text.find(end, pos)
        if i == -1 and j == -1:
            break
        if i == -1 or j == -1 or j < i:
            return None                      # orphan or reversed marker
        if text.find(start, i + len(start), j) != -1:
            return None                      # a second START before this END
        spans.append((i, j + len(end)))
        pos = j + len(end)
    return spans


def upsert(text: str, block: str):
    """Insert/refresh *block* in *text*. Returns (new_text, action).

    action: 'replace' (block existed, body changed), 'noop' (already current),
    'append' (no block present yet), or 'malformed' (markers are orphaned /
    reversed — text returned UNCHANGED; the caller must back up and refuse)."""
    # Prefer the current markers; fall back to the legacy memdag markers so a
    # pre-rename tester's block is migrated in place, not duplicated.
    for start, end in ((START, END), (LEGACY_START, LEGACY_END)):
        if start not in text and end not in text:
            continue
        spans = _find_blocks(text, start, end)
        if not spans:                        # None (malformed) — never write over it
            return text, "malformed"
        # Replace the FIRST block; strip any later duplicates (the historical
        # lost-marker append bug) while keeping the user text between them.
        first_i, first_j = spans[0]
        out = text[:first_i] + block
        prev = first_j
        for i, j in spans[1:]:
            out += text[prev:i]
            prev = j
        out += text[prev:]
        return out, ("noop" if out == text else "replace")
    # no block yet: append, separated by exactly one blank line
    base = text.rstrip("\n")
    sep = "\n\n" if base else ""
    return f"{base}{sep}{block}\n", "append"


# --- IO ----------------------------------------------------------------------

def default_path() -> Path:
    env = os.environ.get("CLAUDE_MD_PATH")
    if env:
        return Path(env).expanduser()
    return Path.home() / ".claude" / "CLAUDE.md"


def _atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)


def sync(path=None, *, dry_run: bool = False) -> dict:
    """Seed / refresh the managed block in CLAUDE.md. Returns a result dict
    {path, action, changed}. Never raises for the absent/present cases; an
    unexpected IO error propagates to the caller (the CLI wraps it fail-safe)."""
    path = Path(path).expanduser() if path else default_path()
    block = render_block()

    if not path.exists():
        new_text, action = render_template(), "seed"
    else:
        existing = path.read_text(encoding="utf-8")
        new_text, action = upsert(existing, block)
        if action == "malformed":
            # Orphan/reversed markers: refuse to touch the file (a rewrite could
            # eat user content), but preserve the evidence for repair.
            bak = path.with_suffix(path.suffix + ".malformed.bak")
            if not dry_run:
                bak.write_text(existing, encoding="utf-8")
            return {"path": str(path), "action": "malformed", "changed": False,
                    "backup": str(bak)}

    changed = action not in ("noop",)
    if changed and not dry_run:
        if action == "append":
            # preserve the user's file before we touch it
            bak = path.with_suffix(path.suffix + ".bak")
            bak.write_text(path.read_text(encoding="utf-8"), encoding="utf-8")
        _atomic_write(path, new_text)
    return {"path": str(path), "action": action, "changed": changed}


# --- CLI ---------------------------------------------------------------------

def _cmd_claude_sync(args):
    if args.print_only:
        print(render_block())
        return
    try:
        res = sync(path=args.path, dry_run=args.dry_run)
    except Exception as exc:  # noqa: BLE001 — never break a hook chain
        print(f"[claude-sync] skipped (CLAUDE.md unchanged): {exc!r}")
        return
    if res["action"] == "malformed":
        print(f"[claude-sync] REFUSED {res['path']}: managed-block markers are "
              f"orphaned or reversed — fix them by hand (copy saved to "
              f"{res['backup']}); file left untouched")
        return
    verb = {"seed": "seeded", "append": "appended block to",
            "replace": "refreshed block in", "noop": "already current:"}[res["action"]]
    print(f"[claude-sync] {verb} {res['path']}")


def register(sub) -> None:
    p = sub.add_parser(
        "claude-sync",
        help="seed/refresh the memsom-managed memory block in CLAUDE.md")
    p.add_argument("--path", default=None,
                   help="CLAUDE.md path (default: $CLAUDE_MD_PATH or ~/.claude/CLAUDE.md)")
    p.add_argument("--print-only", action="store_true",
                   help="print the managed block and write nothing")
    p.add_argument("--dry-run", action="store_true",
                   help="report what would change without writing")
    p.set_defaults(func=_cmd_claude_sync)


def main(argv=None) -> None:
    for s in (sys.stdout, sys.stderr):
        try:
            s.reconfigure(encoding="utf-8")
        except Exception:
            pass  # reconfigure unsupported on this stream — keep its default encoding
    ap = argparse.ArgumentParser(prog="memsom_claude", description=__doc__)
    ap.add_argument("--path", default=None)
    ap.add_argument("--print-only", action="store_true")
    ap.add_argument("--dry-run", action="store_true")
    _cmd_claude_sync(ap.parse_args(argv))


if __name__ == "__main__":
    main()
