"""memsom_audit — deterministic structural integrity audit of the flat memory store.

Read-only, no LLM. The forgetting layer checks whether a memory is still USED and
the staleness pass checks whether its claims still match reality; neither checks
that the store is structurally SOUND. This is that third check — a fast auditor of
the per-fact files that feed the bridge and the generated MEMORY.md index.

Checks (severity):
  orphan-file         ERROR  on disk, live in the store, not in MEMORY.md, and not
                             a deliberate cold demote (DB forget_tier='cold').
  pending-import      INFO   on disk but not yet imported (run `memsom bridge-render`).
  dead-index-link     ERROR  MEMORY.md links a file that isn't on disk.
  frontmatter-missing ERROR  name / description / type missing.
  bad-type            WARN   type not in user/personal/feedback/project/reference/fact.
  budget-breach       WARN   MEMORY.md over the 16384-byte cap.
  needs-cluster       INFO   a new feedback file born unindexed (no why_own_line:).
  broken-wikilink     INFO   a [[link]] with no target (legal by design).

Reuses the bridge importer's parsers, so the audit and the importer agree on what a
memory file and an index entry are. Report-only by design: MEMORY.md is GENERATED by
`memsom bridge-render`, so the fix for a structural issue is to edit the per-fact
file (or let the bridge re-render) — never to hand-patch the generated index.

  memsom audit            # human report (exit 1 if any ERROR)
  memsom audit --json     # machine-readable (drives the /audit skill)
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from memsom.kernel.frontmatter import parse_primary_index
from memsom.kernel.frontmatter import split_frontmatter, fm_top_level
from memsom.kernel.frontmatter import _LINK_IN_LINE
from memsom.kernel.paths import default_memory_dir
from memsom.bridge.bridge_import import (iter_memory_files as _memory_files,
                                         PROJECTS_SUBDIR, unsectioned_by_frontmatter)
from memsom.distill.digest import resolve_budget

BUDGET = 16384  # fallback only; the live cap is resolve_budget(mem_dir)
#                 (`memory_budget` in the store's canonical.json params)
VALID_TYPES = {"user", "personal", "feedback", "project", "reference", "fact"}
# IGNORECASE so detection mirrors the case-folding resolver (_norm); otherwise an
# uppercase target like [[ADHD]] with no match would silently never be flagged.
WIKILINK_RE = re.compile(r"\[\[([a-z0-9][a-z0-9_-]*)\]\]", re.IGNORECASE)
SKIP_FILES = {"MEMORY.md", "MEMORY.memsom.md"}


def _F(name, sev, target, msg):
    return {"name": name, "sev": sev, "target": target, "msg": msg}


def _norm(s):
    """Fold the two identity schemes: filenames use '_', wikilinks/slugs use '-'."""
    return s.replace("_", "-").lower()


def iter_memory_files(mem_dir):
    """(file, stem, frontmatter dict, text) for each per-fact file (excl. the
    indexes) — flat files plus projects/*.md, via the bridge's own walker."""
    for p in _memory_files(mem_dir):
        if p.name in SKIP_FILES:
            continue
        text = p.read_text(encoding="utf-8", errors="replace")
        fm_lines, _body, _ = split_frontmatter(text)
        yield p.name, p.stem, fm_top_level(fm_lines), text


def _store_tiers(mem_dir):
    """(live_stems, cold_stems, db_ok) from the memsom store, best-effort.

    Lets the orphan check tell a deliberate cold demote (fine) from a genuine
    inconsistency (imported + live but missing from the index). If the store is
    unreachable, db_ok=False and the orphan check degrades to a WARN."""
    try:
        import memsom
        from memsom.storage import schema as memsom_schema
        conn = memsom.get_connection()
        try:
            # Rule 5: liveness/taint through the ONE primitive -- a quarantined
            # or redacted memory node is not "live in the store".
            clauses, params = memsom_schema.taint_filter_clauses(conn, clearance=3)
            where = " AND ".join(clauses) + " AND source_ref LIKE 'memory:%'"
            if not memsom_schema.column_exists(conn, "nodes", "forget_tier"):
                # store present but pre-forget schema: treat all imported as live
                rows = conn.execute(
                    f"SELECT source_ref, NULL FROM nodes WHERE {where}", params).fetchall()
            else:
                rows = conn.execute(
                    f"SELECT source_ref, forget_tier FROM nodes WHERE {where}",
                    params).fetchall()
        finally:
            conn.close()
    # FAILOPEN: swallows and returns empty sets -- store unreachable, degrades to WARN (see docstring) instead of crashing the audit.
    except Exception:
        return set(), set(), False
    live, cold = set(), set()
    for sref, tier in rows:
        stem = sref.split(":", 1)[1] if sref.startswith("memory:") else sref
        if stem.startswith("literal:"):
            continue
        live.add(stem)
        if tier == "cold":
            cold.add(stem)
    return live, cold, True


def _shed_reasons(mem_dir):
    """{stem: reason} from the last render's `.weights/shed.json` (the receipt
    bridge_render writes for every index exclusion), or {} when absent or
    unreadable — the receipt may only ever SUPPRESS an orphan, so failing to
    read it makes the audit noisier, never quieter."""
    try:
        data = json.loads((Path(mem_dir) / ".weights" / "shed.json")
                          .read_text(encoding="utf-8"))
        return {e.get("stem"): e.get("reason") for e in data.get("excluded") or []}
    # FAILOPEN: allowed, an absent/unreadable receipt makes the audit noisier, never quieter.
    except Exception:
        return {}


def run_audit(mem_dir):
    mem_dir = Path(mem_dir)
    shed = _shed_reasons(mem_dir)
    files = list(iter_memory_files(mem_dir))
    memory_md = mem_dir / "MEMORY.md"
    md_text = memory_md.read_text(encoding="utf-8") if memory_md.exists() else ""
    hot = set(parse_primary_index(md_text))           # filenames linked in MEMORY.md
    # project memories are indexed in projects/INDEX.md (generated next to
    # MEMORY.md); a file listed there is indexed, not an orphan. Links there are
    # relative to projects/ ("project_x.md" or "../project_x.md") -> basename.
    # INDEX.md links are "x.md", "../x.md" or "<slug>/x.md"; a project group's
    # headline is a "### [..](..)" line, not a bullet, so take EVERY link.
    proj_index = mem_dir / PROJECTS_SUBDIR / "INDEX.md"
    if proj_index.exists():
        hot |= {Path(f).name for f in
                _LINK_IN_LINE.findall(proj_index.read_text(encoding="utf-8"))}
    on_disk = {f for f, *_ in files}
    live, cold, db_ok = _store_tiers(mem_dir)

    findings = []

    # orphan / pending-import / withdrawn
    for fname, stem, fm, _text in files:
        if fname in hot or stem in cold:
            continue
        reason = shed.get(stem)
        if reason == "unsectioned" or unsectioned_by_frontmatter(fm):
            # withdrawn BY DESIGN (`section: none` / `index: false`, or the last
            # render recorded it as unsectioned): out of the index on purpose,
            # still in the store and searchable — informational, never an orphan.
            findings.append(_F("withdrawn", "INFO", fname,
                               "withdrawn from the index on purpose (section: none / "
                               "index: false); still in the store"))
            continue
        if reason == "needs_cluster":
            findings.append(_F("needs-cluster", "INFO", fname,
                               "new feedback file born unindexed (no why_own_line:); "
                               "merge it into a feedback_cluster_* body or run "
                               "`memsom consolidate-feedback`"))
            continue
        if reason in ("budget", "lines", "projects", "section_budget"):
            continue   # explained by the render receipt (shed.json), not an orphan
        if not db_ok:
            findings.append(_F("orphan-file", "WARN", fname,
                               "on disk, not in MEMORY.md; store DB unreachable to "
                               "confirm it isn't a deliberate cold demote"))
        elif stem not in live:
            findings.append(_F("pending-import", "INFO", fname,
                               "on disk but not yet imported — run `memsom bridge-render`"))
        else:
            findings.append(_F("orphan-file", "ERROR", fname,
                               "live in the store but absent from MEMORY.md and not a "
                               "cold demote (the index and the store disagree)"))

    # dead index link
    for fname in sorted(hot):
        if fname not in on_disk:
            findings.append(_F("dead-index-link", "ERROR", fname,
                               "linked in MEMORY.md but the file is missing "
                               "(restore the file or remove the line)"))

    # frontmatter + type
    for fname, _stem, fm, _text in files:
        missing = [k for k in ("name", "description", "type") if not fm.get(k)]
        if missing:
            findings.append(_F("frontmatter-missing", "ERROR", fname,
                               f"missing frontmatter key(s): {', '.join(missing)}"))
        typ = fm.get("type", "")
        if typ and typ not in VALID_TYPES:
            findings.append(_F("bad-type", "WARN", fname,
                               f"type '{typ}' not in {sorted(VALID_TYPES)}"))

    # broken wikilinks (INFO; legal by design)
    resolvable = set()
    for _fname, stem, fm, _text in files:
        resolvable.add(_norm(stem))
        if fm.get("name"):
            resolvable.add(_norm(fm["name"]))
    broken = {}
    for fname, _stem, _fm, text in files:
        for tgt in WIKILINK_RE.findall(text):
            if _norm(tgt) not in resolvable:
                broken.setdefault(tgt, set()).add(fname)
    for tgt, srcs in sorted(broken.items()):
        ex = ", ".join(sorted(srcs)[:3]) + ("…" if len(srcs) > 3 else "")
        findings.append(_F("broken-wikilink", "INFO", tgt,
                           f"[[{tgt}]] has no target (referenced by {len(srcs)}: {ex})"))

    # budget (live cap from canonical.json params, falling back to BUDGET)
    if memory_md.exists():
        size = memory_md.stat().st_size
        cap = resolve_budget(mem_dir)
        if size > cap:
            findings.append(_F("budget-breach", "WARN", "MEMORY.md",
                               f"{size} bytes > {cap} cap (over by {size - cap})"))

    # structured project memory: fold in project.check (audit-shaped findings —
    # project-schema/alias-clash/creds-value ERROR, loose-file/nested-frontmatter
    # WARN, stale-status INFO). Down-rank import (interface -> bridge).
    try:
        from memsom.bridge import project as _project
        findings += _project.check(mem_dir)
    # FAILOPEN: project checks are additive — a bug in them degrades to one INFO the operator sees, never a crash of the whole store audit.
    except Exception as exc:
        findings.append(_F("project-check", "INFO", "projects/",
                           f"project check skipped: {exc!r}"))

    return findings, files, (md_text, db_ok)


# --- reporting ---------------------------------------------------------------
SEV_ORDER = {"ERROR": 0, "WARN": 1, "INFO": 2}
SEV_MARK = {"ERROR": "x ERROR", "WARN": "! WARN ", "INFO": ". INFO "}


def section_counts(mem_dir, md_text=None) -> dict:
    """Per-section {lines, bytes, budget} for the on-disk MEMORY.md (anti-creep
    mechanism 4 — the same table bridge-render prints and shed.json carries)."""
    from memsom.distill.digest import section_stats, resolve_section_budgets
    from memsom.bridge.bridge_render import section_table
    if md_text is None:
        memory_md = Path(mem_dir) / "MEMORY.md"
        md_text = memory_md.read_text(encoding="utf-8") if memory_md.exists() else ""
    return section_table(section_stats(md_text), resolve_section_budgets(mem_dir))


def print_report(findings, files, mem_dir, md_text):
    memory_md = Path(mem_dir) / "MEMORY.md"
    sz = memory_md.stat().st_size if memory_md.exists() else 0
    cap = resolve_budget(mem_dir)
    print(f"\n  memsom audit — {mem_dir}")
    print(f"  {len(files)} memories | MEMORY.md {sz}/{cap} bytes "
          f"(headroom {cap - sz})")
    for sec, st in section_counts(mem_dir, md_text).items():
        cap_s = f" (budget {st['budget']})" if st["budget"] is not None else ""
        over = "  OVER" if st["budget"] is not None and st["bytes"] > st["budget"] else ""
        print(f"    {sec}: {st['lines']} lines / {st['bytes']} bytes{cap_s}{over}")
    print()
    if not findings:
        print("  clean — no structural issues.\n")
        return
    for f in sorted(findings, key=lambda x: (SEV_ORDER[x["sev"]], x["name"], x["target"])):
        print(f"  {SEV_MARK[f['sev']]}  [{f['name']}] {f['target']}")
        print(f"            {f['msg']}")
    n = {s: sum(1 for f in findings if f["sev"] == s) for s in SEV_ORDER}
    print(f"\n  summary: {n['ERROR']} error, {n['WARN']} warn, {n['INFO']} info\n")


def _cmd_audit(args):
    import os
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8")
        # FAILOPEN: swallows and continues -- reconfigure unsupported on this stream, keep its default encoding.
        except Exception:
            pass
    # Friend-beta convention: the store lives in ~/.memdag unless MEMDAG_DB is set,
    # so the cold-tier refinement reads the real store with no env wiring.
    os.environ.setdefault("MEMDAG_DB", str(Path.home() / ".memdag" / "memdag.db"))
    mem_dir = Path(args.memory_dir) if args.memory_dir else default_memory_dir()
    findings, files, (md_text, _db_ok) = run_audit(mem_dir)
    if args.json:
        sz = (Path(mem_dir) / "MEMORY.md").stat().st_size \
            if (Path(mem_dir) / "MEMORY.md").exists() else 0
        print(json.dumps({
            "mem_dir": str(mem_dir),
            "memories": len(files),
            "memory_md_bytes": sz,
            "budget": resolve_budget(mem_dir),
            "sections": section_counts(mem_dir, md_text),
            "findings": findings,
            "errors": sum(1 for f in findings if f["sev"] == "ERROR"),
        }, indent=2))
    else:
        print_report(findings, files, mem_dir, md_text)
    return 1 if any(f["sev"] == "ERROR" for f in findings) else 0


def register(sub) -> None:
    p = sub.add_parser("audit",
                       help="structural integrity audit of the flat memory store (read-only)")
    p.add_argument("memory_dir", nargs="?", default=None,
                   help="memory dir (default: auto-detected ~/.claude/projects/*/memory)")
    p.add_argument("--json", action="store_true", help="machine-readable output (for /audit)")
    p.set_defaults(func=_cmd_audit)


def main(argv=None) -> None:
    ap = argparse.ArgumentParser(prog="memsom_audit", description=__doc__)
    ap.add_argument("memory_dir", nargs="?", default=None)
    ap.add_argument("--json", action="store_true")
    sys.exit(_cmd_audit(ap.parse_args(argv)))


if __name__ == "__main__":
    main()
